# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 04:17
from __future__ import unicode_literals

import blog.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171104_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content2',
            field=blog.fields.CompressedTextField(default='', null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='labels',
            field=blog.fields.ListField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
